blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/USERNAME/hermes-docgen/discussions
    about: Use GitHub Discussions for questions, ideas and discussions